crawler/index.ts
db/index.ts

[Task](https://hadronlabs.atlassian.net/browse/DRP-154)

feat: place calc #DRP-154

---

config.toml.sample
db/index.ts
server/controllers/getRules/index.ts
types/config/dropletRule.ts

- Support for frontend invisible rules
- Config refactoring
Task is: https://hadronlabs.atlassian.net/browse/DRP-180

feat: support invisible rules #DRP-180

---

db/index.ts
server/controllers/getKVData/index.ts
server/controllers/postKVData/index.ts
server/index.ts
types/tRPC/tRPCGetKVData.ts
types/tRPC/tRPCPostKVData.ts

[Task](https://hadronlabs.atlassian.net/browse/DRP-210)

feat: kv storage

---

crawler/index.ts
lib/kyc/index.ts
server/controllers/postKyc/index.ts

[Task](https://hadronlabs.atlassian.net/browse/DRP-218)
inserting kyc info
getting info

feat: local kyc insert

---

Dockerfile
backup.sh
drop-points-local.sh
drop-points-publish.sh
server/index.ts

Task is: https://hadronlabs.atlassian.net/browse/DRP-261

feat: Set up crawler a little bit more #DRP-261

---

crawler/index.ts
server/controllers/getDroplets/index.ts

Task is: https://hadronlabs.atlassian.net/browse/DRP-312

fix: Referral points are not publishing #DRP-312

---

crawler/index.ts

Task is: https://hadronlabs.atlassian.net/browse/DRP-340

fix: Additional referral points are added to the referrers #DRP-340

---

lib/sources/index.ts
lib/sources/liquidity-alliance-compounder/index.ts
lib/sources/liquidity-alliance/index.ts

This is the config to add the dATOM/ATOM pool from Astroport and WW Single Asset Gauge + Compounder to Droplet points. RPC has been redacted and sent via TG group.
``` toml
[protocols.terra-liquidity-alliance]
rpc = "https://redacted.../"
source = "liquidity-alliance"
jitter = 10000
pagination_limit = 10000
[protocols.terra-liquidity-alliance.assets.dATOM]
multiplier = 5
denom = "ibc/223FF539430381ADAB3A66AC4822E253C3F845E9841F17FEEC207B3AA9F8D915"
pair_contract = "terra1a0h6vrzkztjystg8sd949qyrc6mw9gzxk2870cr2mukg53uzgvqs46qul9"
staking_contract = "terra1qdz5qgafx88kp5mf6m2tah8742g4u5g2cek0m3jrgssexexk7g4qw6e23k"
lp_token = "cw20:terra12mvtdvn4fgtsqs4fwxr56vcwjw0xe23lhdfyjq5ghk7vmfeuxn0srau9q2"
[protocols.terra-liquidity-alliance.assets.dATOM_WW]
multiplier = 5
denom = …
```

Integrate Terra Liquidity Alliance

---

crawler/random.ts

Simplify pseudo random jitter even more

Pseudo random jitter - 2

---

server/controllers/getDroplets/index.ts

Fix output validation error - 2

---

crawler/index.ts

Boosters are applied for change
Task is: https://hadronlabs.atlassian.net/browse/DRP-441

#DRP-441 Change displayed incorrectly in case of NFT boosters [fix]

---

lib/pricefeed.ts
lib/sources/index.ts
lib/sources/levana-trade/index.ts
lib/sources/milkyway/index.ts
types/sources/levanaTradeFeesReport.ts

Task is: https://hadronlabs.atlassian.net/browse/DRP-451
Levana trade source for droplets
```
[protocols.levana-trade]
rpc = "https://rpc-kralum.neutron-1.neutron.org:443/"
source = "levana-trade"
reports_url = "https://trade-fee-reports.pages.dev"
supply = 1000000000
[protocols.levana-trade.assets.USD]
multiplier = 1
```
```
insert into schedule (schedule_id, protocol_id, asset_id, multiplier, start, end, enabled) values (46, 'levana-trade', 'USD', 1, 0, 0, true);
insert into user_points_rules (strategy, description, multiplier, chain, status, link, link_text, type, featured, visible) values ('Trade', 'Trading fees in USD on Levana', 1, 'neutron', 1, 'https://www.levana.finance', 'Go to Levana', 'single-sided', 0, 1);
```

feat: Levana trade source 📈 #DRP-451

---

crawler/index.ts

also need to add 
```toml
[protocols.madscientists]
type = "nft"
source = "stargaze"
rpc = "https://stargaze-rpc.polkachu.com:443/"
jitter = 1000
concurrency_limit = 10
contract = "stars1v8avajk64z7pppeu45ce6vv8wuxmwacdff484lqvv0vnka0cwgdqdk64sf"
[protocols.madscientists.assets.dATOM]
multiplier = 1.1
[protocols.madscientists.assets.dTIA]
multiplier = 1.1
```
```sql
INSERT INTO schedule (protocol_id,asset_id,multiplier,"start","end",enabled) VALUES
('madscientists','dATOM',1.1,1740697180,1838001973,1),
('madscientists','dTIA',1.1,1740697180,1838001973,1);
```

feat: nft cap

---

lib/sources/index.ts
lib/sources/osmo-staked/index.ts
server/controllers/getNFTCollections/index.ts

```toml
[protocols.madscientists-osmo-staked]
type = "nft"
source = "osmo-staked"
rpc = "https://osmosis-rpc.polkachu.com:443/"
jitter = 1000
concurrency_limit = 10
contract = "osmo1hcmh6vr2etuqr0js0fzfmsdqgn829r8gu96l9puh3465628n036qqg8xk6"
[protocols.madscientists-osmo-staked.assets.dATOM]
multiplier = 1.1
[protocols.madscientists-osmo-staked.assets.dTIA]
multiplier = 1.1
```
```sql
INSERT INTO schedule (protocol_id,asset_id,multiplier,"start","end",enabled) VALUES
('madscientists-osmo-staked','dATOM',1.1,1740697180,1838001973,1),
('madscientists-osmo-staked','dTIA',1.1,1740697180,1838001973,1);
```

feat: osmo staked nfts

---

crawler/index.ts

- Refactoring
- Atomicity of the prepare command

Fix atomicity of the prepare command

---

crawler/index.ts
lib/sources/agoric/index.ts

- Fix for Agoric Inter source
- Publish on chain skipped if there are batches with status 'new'

Fixes to the recent issues

---

db/index.ts
server/controllers/deleteDoMore /index.ts
server/controllers/getDoMore/index.ts
server/controllers/postDoMore/index.ts
server/index.ts
types/tRPC/tRPCDeleteDoMore.ts
types/tRPC/tRPCGetDoMore.ts
types/tRPC/tRPCPostDoMore.ts

```
$ curl http://127.0.0.1:3000/getDoMore --header "Authorization: Bearer ***"
{"result":{"data":[{"id":1,"asset1":"one","asset2":"two","description":"wowow","multiplier":1.123,"aprMin":11123,"aprMax":123,"link":"liiink","order":123},{"id":2,"asset1":"one","asset2":"two","description":"wowow","multiplier":1.123,"aprMin":11123,"aprMax":123,"link":"liiink","order":123},{"id":3,"asset1":"one","asset2":"two","description":"wowow","multiplier":1.123,"aprMin":11123,"aprMax":123,"link":"liiink","order":123},{"id":4,"asset1":"one","asset2":"two","description":"wowow","multiplier":1.123,"aprMin":11123,"aprMax":123,"link":"liiink","order":123},{"id":5,"asset1":"one","asset2":"two","description":"wowow","multiplier":1.123,"aprMin":11123,"aprMax":123,"link":"liiink","order":123}]}}
$ curl -X POST …
```

💅 do more with drop stuff for frontend

---

lib/sources/osmo-staked/index.ts
lib/sources/stargaze/index.ts

Throwing an error in case of NFTs fetching fail

🛠️ NFT processing fix

---

lib/sources/agoric/index.ts

Add one more collateral attribute

fix: inter collaterals

---

crawler/index.ts
lib/referral/index.ts

config.toml
```toml
newcomers_stake_start = 472
```
```sql
UPDATE badges SET mul=1.25 WHERE id='newcomer';
```

feat: newcomers stake

---

lib/link/index.ts

Fix excess deletion from user network links

Fix initia address linking

---

lib/pricefeed.ts

```toml
[pricefeed.assets.deINIT]
offchain = true
pyth_id = "b86ddb07a6163b55cdee9a676131dc28d2faea445060ac3a28c687ed42db6e84"
core_contract = "neutron1yy6pqu5ex3kusmnc7z50rkdcpwtyds5k5g6u95rr0w80cxaay00qau6jls"
usd_part = 0.2
```

feat: support deINIT LP price

---

server/controllers/getAirdropInfo/index.ts
server/controllers/getRankTable/index.ts
server/index.ts
types/tRPC/tRPCGetAirdropInfo.ts
types/tRPC/tRPCGetRankTable.ts

Ranking overall all user points public tables

Add airdrop info controller: ranking 🥇

---

lib/pricefeed.ts

```toml
[pricefeed]
jitter = 1000
rpc = "https://rpc-kralum.neutron-1.neutron.org:443/"
contract = "neutron1m2emc93m9gpwgsrsf2vylv9xvgqh654630v7dfrhrkmr5slly53spg85wv"
[pricefeed.assets.maxBTC]
type = "flat"
core_contract = "neutron17sp75wng9vl2hu3sf4ky86d7smmk3wle9gkts2gmedn9x4ut3xcqa5xp34"
exchange_rate_query = "{\"exchange_rate\": {}}"
```

feat: flat price for maxbtc
